'use strict';
//List of Web of Science Field Tags
module.exports = {
  FieldTag:{
    FN:'File type',
    VR:'File format version number',
    PT:'Publication type (e.g., book, journal, book in series)',
    AU:'Author(s)',
    AF:'Author Full Name',
    AR:'Article Number',
    BN:'International Standard Book Number (ISBN)',
    CA: 'Group Authors',
    TI:'Article title',
    ED: 'Editors',
    SO:'Full source title',
    HO:'International Standard Book Number (ISBN)',
    LA:'Language',
    DT:'Document type',
    NR:'Cited reference count',
    SN:'ISSN',
    SP:'Conference Sponsors',
    PU:'Publisher',
    C1:'Author address',
    CL:'Conference Location',
    CY:'Conference Date',
    CT:'Conference Title',
    D2:'Book Digital Object Identifier (DOI)',
    DE:'Author keywords',
    ID:'KeyWords Plus',
    AB:'Abstract',
    CR:'Cited references',
    TC:'Times cited',
    BP:'Beginning page',
    BE:'Editors',
    BA:'Book Authors',
    EP:'Ending page',
    PG:'Page count',
    JI:'ISO source title abbreviation',
    SE:'Book series title',
    BS:'Book series subtitle',
    PY:'Publication year',
    P2:'Chapter Count (Book Citation Index)',
    PD:'Publication date',
    VL:'Volume',
    IS:'Issue',
    PN:'Part number',
    SU:'Supplement',
    SI:'Special issue',
    GA:'ISI document delivery number',
    GP:'Book Group Authors',
    PI:'Publisher city',
    WP:'Publisher web address',
    RP:'Reprint address',
    CP:'Cited patent',
    J9:'29-character source title abbreviation',
    PA:'Publisher address',
    UT:'ISI unique article identifier',
    DI:'Digital Object Identifier (DOI)',
    EM:'Email address',
    FU:'Funding Agency and Grant Number',
    SC:'Subject Category',
    FX:'Funding Text',
    WC:'Web of Science Category',
    Z9:'Total Times Cited Count (WoS, BCI, and CSCD)',
    ER:'End of record',
    EF:'End of file'
  }
};
