#!/usr/bin/env node
'use strict';
var FieldTag=require('./config').FieldTag;
var _ = require('lodash');
var rdf = require('rdf');
var env=rdf.environment;
var Graph=rdf.Graph;
var rdfns=rdf.rdfns;

env.setPrefix("risis", "http://risis.eu/");
env.setPrefix("doi", "http://dx.doi.org/");
env.setPrefix("wosV", "http://risis.eu/wos/vocab/");
env.setPrefix("skos", "http://www.w3.org/2004/02/skos/core#");

rdf.setBuiltins();
var g= new Graph;

_.forEach(FieldTag, function(comment, tag) {
  g.add(env.createTriple('wosV:'+tag, 'rdfs:label', tag.l()));
  g.add(env.createTriple('wosV:'+tag, 'rdfs:comment', comment.l()));
});
//return graph in NT format
var NT = g.toArray().map(function(t){
    return t.toString() + "\n";
}).join('');
console.log(NT);
