#!/bin/bash
source="./test/dump/1"
dest="./test/dump/rdf"
for dir in "$source"/*; do
  if [ -d "$dir" ]; then
    for f in "$dir"/*.txt; do
      filename=$(basename "$f")
      extension="${filename##*.}"
      filename="${filename%.*}"
      if [ ! -e "$dest/$filename.n3" ]; then
        echo " coverting \"$f\" to RDF...";
        ./tsv_n3 "$f" > "$dest/$filename.n3";
        #./isi_n3 "$f" > "../test/dump/rdf/$filename.n3";
        echo " done... RDF available at $dest/$filename.n3";
      fi
    done
  fi
done
